name: Validate & Publish Badge Database

on:
  push:
    branches:
      - master
    paths:
      - "badges.jsonc"
      - "validateDB.js"
      - "buildJSON.js"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "badges.jsonc"
      - "validateDB.js"
      - "buildJSON.js"
      - ".github/workflows/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
  validate-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Validate badges.jsonc
        run: node validateDB.js

      - name: Build badges.json
        run: node buildJSON.js

      - name: Create Pages directory
        run: |
          mkdir site
          cp badges.json site/

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v5
        with:
          path: site

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v5
